name: "GitHubActions-HCP-Terraform"
run-name: ${{ github.actor }} has triggered the Apply pipeline
# Controls when the action will run. Invokes the workflow on push events but only for the main branch and on pull requests that modify Terraform files
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: ["**.tf", "**.tfvars"]
    types: [opened, synchronize, reopened]

# Permission can be added at job level or at workflow level
permissions:
  id-token: write # This is required for requesting the JWT token from GitHub IdP
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR
  actions: read
  checks: write
  issues: write # Ensure this is added

jobs:
  terraform_IaC_deploy:
    name: "GitHub Actions_Terraform_IaC_Deploy_to_AWS_via_HCP_Terraform_Cloud"
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_ORGANIZATION: "cloud-infra-dev"
      TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
      TF_WORKSPACE: "github-actions-oidc-hcp-terraform"
      CONFIG_DIRECTORY: "./"
      TF_LOG: INFO
      AWS_REGION: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        shell: bash
    #   working-directory: .

    steps:
      - name: "Checkout code from Repository (same as git clone)"
        uses: actions/checkout@v4

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: plan-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          speculative: true

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ secrets.ROLE_SESSION_NAME}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify IAM Role Assumption
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.14.0

      - name: Terraform Init
        id: init
        run: |
          echo -e "access_key = \"${AWS_ACCESS_KEY_ID}\"\nsecret_key = \"${AWS_SECRET_ACCESS_KEY}\"\ntoken = \"${AWS_SESSION_TOKEN}\"\nregion = \"${AWS_REGION}\"" | tee credentials.auto.tfvars
          terraform init
        env:
          TF_LOG: ERROR

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt --recursive

      - name: Terraform Validate
        id: validate
        run: terraform validate
        env:
          TF_LOG: ERROR

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -var-file="credentials.auto.tfvars" -input=false -out=tfplan
        continue-on-error: true # "continue-on-error: true" ensures the workflow continues even if the plan fails, so you still get feedback about what went wrong
        env:
          TF_VAR_read_only: true
          TF_LOG: ERROR

      - name: Save Terraform Plan Output
        if: github.event_name == 'pull_request'
        run: terraform show -json tfplan > plan.json
        env:
          TF_LOG: ERROR

      - name: Create PR Comment with Plan Output
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const planOutput = fs.readFileSync('plan.json', 'utf8');
            const comment = `### Terraform Plan Result\n\`\`\`json\n${planOutput}\n\`\`\``;
            const issue_number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: comment,
            });

      # On push to "main", build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -var-file="credentials.auto.tfvars" -auto-approve -input=false
        env:
          TF_LOG: ERROR
